apps/matching/urls.py
from django.urls import path
from . import views

app_name = 'matching'

urlpatterns = [

    path('', views.main, name = "main"),
    path('create/', views.matching_create, name="create"),
    path('apply/room/<int:pk>', views.matching_apply, name="apply"),
    path('update/room/<int:pk>', views.matching_update, name="update"),
    path('delete/room/<int:pk>', views.matching_delete, name="delete"),
    path('detail/room/<int:pk>', views.matching_detail, name="detail"),
    path('history/', views.matching_history, name="history"),
    path('alarm-delete/<int:alarm_id>/', views.alarm_delete, name="alarm-delete"),
    path('questions/', views.questions, name="questions"),
]

taxiRoka/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='matching/')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('chat/', include('apps.chat.urls')),
    path('matching/', include('apps.matching.urls')),
    path('user/', include('apps.user.urls')),
    path('vacation/', include('apps.vacation.urls')),
    path('report/', include('apps.report.urls')),
]

apps/matching/models.py
from django.db import models
from apps.user.models import CustomUser 


# ERD CLOUD 링크: https://www.erdcloud.com/d/zB3wiAaQY7PxnzLyY

class MatchingRoom(models.Model):
    # 출발날짜, 출발시간, 출발지, 도착지, 최대인원수, 현재인원수, 매칭방생성일, 매칭방 생성/종료 여부
    departure_date = models.DateField()
    departure_time = models.TimeField()
    departure_area = models.CharField(max_length=10)
    destination_area = models.CharField(max_length=10)
    max_num = models.IntegerField()
    current_num = models.IntegerField()
    create_date = models.DateTimeField(auto_now_add=True)
    end_yn = models.BooleanField()
    uuid = models.CharField(max_length=36)

class Matching(models.Model):
    # 매칭방식별자, 유저식별자, 방장여부, 좌석번호, 매칭일, 익명
    matching_room_id = models.ForeignKey(MatchingRoom, on_delete=models.CASCADE)
    user_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE) 
    host_yn = models.BooleanField()
    seat_num = models.IntegerField()
    matching_date = models.DateTimeField()
    anon_name = models.CharField(max_length=10)

class Alarm(models.Model):
    # 알림식별자, 유저 외래키, 알림 내용, 매칭방 외래키
    user_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE) 
    matching_room_id = models.ForeignKey(MatchingRoom, on_delete=models.CASCADE)
    content = models.CharField(max_length=30)

apps/matching/views.py
from django.shortcuts import render, redirect
from .models import *
from apps.user.models import *
from apps.vacation.models import *
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from datetime import datetime, timedelta
import json
import uuid
import random

# 매칭 방 리스트
def main(request):

    now = timezone.now()

    if request.user.is_authenticated:
        if not request.user.location:
            return redirect('user:social_login')
        user_location = request.user.location
        rooms = MatchingRoom.objects.filter(matching__user_id__location = user_location, end_yn = True).distinct()

        # 날짜 선택 안 했을 시
        rooms = rooms.order_by("departure_date", "departure_time", "create_date")

        # 현재 유저가 host인 방에 대한 리스트
        is_host = list() 
        for room in rooms:
            matching = Matching.objects.filter(matching_room_id = room, user_id = request.user, host_yn = True).exists()
            if matching:
                is_host.append(room)
            # 현재 시각이 매칭방의 출발시간으로부터 3시간 뒤라면 end_yn = False가 된다.
            departure_datetime = datetime.combine(room.departure_date, room.departure_time)
            departure_datetime = timezone.make_aware(departure_datetime)
            if now >= departure_datetime + timedelta(hours=3):
                room.end_yn = False
                room.save()
        rooms = rooms.filter(end_yn = True) 

        selected_date = request.GET.get("selected_date")

        if selected_date:
            selected_date = timezone.datetime.strptime(selected_date, '%Y-%m-%d').date()
            rooms = rooms.filter(departure_date = selected_date)
        
        # 날짜 정보
        # today = datetime.date.today()

        # 이미 신청했는지 여부 판단
        already_apply_ids = Matching.objects.filter(matching_room_id__in=list(rooms), user_id=request.user, host_yn=False).values_list('matching_room_id', flat=True)

        pagetype = 1
        ctx = {
            'rooms':rooms,
            'pagetype':json.dumps(pagetype),
            'is_host':is_host,
            'already_apply_ids': already_apply_ids,
        }

        return render(request, 'matching/matchinglist.html', context=ctx)

    else:
        rooms = MatchingRoom.objects.filter(end_yn = True)
        rooms = rooms.order_by("departure_date", "departure_time", "create_date")

        selected_date = request.GET.get("selected_date")
        if selected_date:
            selected_date = timezone.datetime.strptime(selected_date, '%Y-%m-%d').date()
            rooms = rooms.filter(departure_date = selected_date)
        
        # end_yn = True 판단
        for room in rooms:
            departure_datetime = datetime.combine(room.departure_date, room.departure_time)
            departure_datetime = timezone.make_aware(departure_datetime)
            if now >= departure_datetime + timedelta(hours=3):
                room.end_yn = False
                room.save()
        rooms = rooms.filter(end_yn=True)

        pagetype = 1
        ctx = {
            'rooms':rooms,
            'pagetype':json.dumps(pagetype),
        }

        return render(request, 'matching/matchinglist.html', context=ctx)
    

# 매칭 방 생성
@login_required
def matching_create(request):
    # 방 생성은 3번까지만 가능
    if Matching.objects.filter(user_id = request.user, matching_room_id__end_yn = True).count()>=3:
        return render(request, "matching/createroom.html", {'create_limit': True})

    if request.method == 'POST':
        # print("create요청성공")

        departure_area = request.POST.get("departure_area")
        destination_area = request.POST.get("destination_area")
        departure_date = request.POST.get("departure_date")
        departure_time = request.POST.get("departure_time")
        seat_num = request.POST.get("seat_num")
        max_num = request.POST.get("max_num")

        # 클라이언트가 넘긴 값에 대한 유효성 검사
        context = validate_matching_info(departure_area, destination_area, departure_date, departure_time, seat_num, max_num)
        if context:
            return render(request, "matching/createroom.html", context = context)

        matching_room = MatchingRoom.objects.create(
            departure_area = departure_area,
            destination_area = destination_area,
            departure_date = departure_date,
            departure_time = departure_time,
            max_num = request.POST["max_num"],
            current_num = 1,
            end_yn =True,
            uuid =uuid.uuid4(),
        )
        # print("방생성 룸아이디:", matching_room.id)

        Matching.objects.create(
            matching_room_id=matching_room,
            user_id=request.user,
            host_yn=True,
            seat_num=seat_num,
            matching_date=timezone.now(),
            anon_name=getAnonName(matching_room.id)
        )

        #alarm
        alarm_type = "matching_create"
        alarm_activate(matching_room, alarm_type)

        return redirect('/matching/history/')
    
    return render(request, "matching/createroom.html")

# 매칭 신청하기
@login_required
def matching_apply(request, pk):
    # 방 신청 제한
    if Matching.objects.filter(user_id = request.user, matching_room_id__end_yn = True).count()>=3:
        return render(request, "matching/matching_apply.html", {'create_limit': True})

    matching_room = MatchingRoom.objects.get(id=pk)
    selected_seats = list(Matching.objects.filter(matching_room_id=matching_room).values_list('seat_num', flat=True)) # 이미 선택된 좌석들(더 좋은 방법이 없을까..?)
    user = request.user
    #이미 신청한 방인지 여부 파악
    already_apply = Matching.objects.filter(matching_room_id = matching_room, user_id = request.user).exists()
    
    if already_apply or matching_room.current_num == matching_room.max_num:
        return redirect('/matching/')
    
    #매칭방 정보를 넘겨주어 그 방에 있는 유저들을 파악하고 알림 테이블에 정보 저장
    

    if request.method == 'POST':
        seat_num = request.POST.get("seat_num")

        # 클라이언트가 넘긴 값에 대한 유효성 검사
        context = validate_matching_seat(seat_num)
        if context:
            context['matching_room'] = matching_room
            context['selected_seats'] = json.dumps(selected_seats)
            return render(request, 'matching/matching_apply.html', context = context)

        alarm_type = "matching_apply"
        alarm_activate(matching_room, alarm_type)

        #신청자 Matching객체 생성해주기
        Matching.objects.create(
            matching_room_id=matching_room,
            user_id=user,
            host_yn=False,
            seat_num=seat_num,
            matching_date=datetime.now(),
            anon_name=getAnonName(matching_room.id)
        )
        
        #신청자 수 1증가
        matching_room.current_num += 1

        #현재 인원이 최대 인원 수와 같아진다면 매칭방 종료
        #if matching_room.current_num == matching_room.max_num:
        #    matching_room.end_yn = False

        matching_room.save()
        # history페이지 or 로 연결되게 바꿀 것(영진)
        return redirect('/matching/')
    else:
        ctx = {
            'matching_room': matching_room,
            'selected_seats': json.dumps(selected_seats), #jsno화
            'already_apply':already_apply
        }
        return render(request, 'matching/matching_apply.html', context=ctx)

# 매칭방 수정하기
@login_required
def matching_update(request, pk):
    user = request.user
    matching_room = MatchingRoom.objects.get(id=pk)
    is_host = Matching.objects.get(matching_room_id = matching_room, host_yn = True)
    is_guest = Matching.objects.filter(matching_room_id = matching_room, host_yn = False).exists()
    selected_seats = list(Matching.objects.filter(matching_room_id=matching_room).values_list('seat_num', flat=True))
    current_num = matching_room.current_num
    max_num = int(matching_room.max_num)
    

    # 현재 인원수보다 적게 max_num을 변경할 수는 없음 (추후에 변경해야 될 하드코딩)
    if current_num == 4:
        change_yn = False
    else:
        change_yn = True

    # 이미 매칭 완료된 방은 수정 불가능
    #if current_num == max_num:
    #   return redirect('/matching/')

    if is_host.user_id == user:
        if request.method == 'POST':
            if not is_guest:  # 방장만 존재하는 경우
                
                departure_area = request.POST.get("departure_area")
                destination_area = request.POST.get("destination_area")
                departure_date = request.POST.get("departure_date")
                departure_time = request.POST.get("departure_time")
                seat_num = request.POST.get("seat_num")
                max_num = request.POST.get("max_num")

                # 클라이언트가 넘긴 값에 대한 유효성 검사
                context = validate_matching_info(departure_area, destination_area, departure_date, departure_time, seat_num, max_num)
                if context:
                    context['matching_room'] = matching_room
                    context['selected_seats'] = json.dumps(list(seat_num))
                    context['ret_bec_error'] = True
                    return render(request, "matching/matching_update.html", context = context)

                matching_room.departure_area = departure_area
                matching_room.destination_area = destination_area
                matching_room.departure_date = departure_date
                matching_room.departure_time = departure_time
                matching_room.max_num = max_num
                matching_room.save()

                is_host.seat_num = seat_num
                is_host.save()

                return redirect('/matching/')
            else:     # 방장 외 인원이 존재하는 경우
                matching_room.max_num = request.POST["max_num"]
                matching_room.save()
                
                is_host.seat_num = request.POST['seat_num']
                is_host.save()
                alarm_type = "matching_update"
                alarm_activate(matching_room, alarm_type)

                return redirect('/matching/')
        else:
            ctx={
                'matching_room':matching_room,
                'selected_seats':json.dumps(selected_seats),
                'change_yn':change_yn,

templates/matching/createroom.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% endblock %}

{% block content %}
<!-- 모달 창 -->
{% if create_limit %}
<div class="modal fade" id="maxRoomsModal" tabindex="-1" aria-labelledby="maxRoomsModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="maxRoomsModalLabel">방 생성 제한</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                이미 3개 이상의 방에 참여하셨습니다. 더 이상 방을 생성할 수 없습니다.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        // 모달 띄우기
        $('#maxRoomsModal').modal('show');
    });
    $('#maxRoomsModal').on('hidden.bs.modal', function () {
            window.location.href = "{% url 'matching:main' %}";
        });
</script>

{% endif %}
<div class="create-room">
    <form class="create-room-form" action="{% url 'matching:create' %}" method="post">
        {% csrf_token %}
        <div>
            <div class="direction-container">
                <div class="form-floating locations">
                    <input class="form-control" id="departure-area" name="departure_area" value="{{ departure_area }}">
                    <label for="departure_area">출발 지점을 입력하세요.</label>
                </div>
                <img class="img-direction" src="{% static 'img/moveto.png' %}" alt="Image 2">
                <div class="form-floating locations">
                    <input class="form-control" id="destination-area" name="destination_area" value="{{ destination_area }}">
                    <label for="destination_area">도착 지점을 입력하세요.</label>
                </div>
            </div>
            <p class="error-msg">{{ error_msg_area }}</p>
            
        </div>
        <hr>
        <div class="create-date-container">
            <div class="create-departure_date">
                <p>출발일</p>
                <input type="date" name="departure_date" id="departure-date" value="{{ departure_date }}">
            </div>
            <p class="error-msg">{{ error_msg_date_date }}</p>
        </div>
        <hr>
        <div class="create-date-container">
            <div class="create-departure_time">
                <p>시간</p>
                <input type="time" id="departure-time" name="departure_time">
            </div>
            <p class="error-msg">{{ error_msg_date_time }}</p>
        </div>
        <hr>


        <div class="create-container">
            <p>좌석 선택</p>
            <div class="create-option">
                <div class="seat-container">
                    <label for="rating0" class="seat-option">
                        <img src="{% static 'img/selected_seat.png' %}" alt="Image 0" class="disabled">
                    </label>
                    <input type="radio" name="seat_num" id="rating1" value="1" class="hidden-radio" {% if seat_num == "1" %}checked{% endif %}>
                    <label for="rating1" class="seat-option">
                        {% if seat_num == "1" %}
                        <img src="{% static 'img/selected_seat.png' %}" alt="Image 1">
                        {% else %}
                        <img src="{% static 'img/seat.png' %}" alt="Image 1">
                        {% endif %}
                    </label>

                </div>
                <div class="seat-container">
                    <input type="radio" name="seat_num" id="rating2" value="2" class="hidden-radio" {% if seat_num == "2" %}checked{% endif %}>
                    <label for="rating2" class="seat-option">
                        {% if seat_num == "2" %}
                        <img src="{% static 'img/selected_seat.png' %}" alt="Image 2">
                        {% else %}
                        <img src="{% static 'img/seat.png' %}" alt="Image 2">
                        {% endif %}
                    </label>
                    <input type="radio" name="seat_num" id="rating3" value="3" class="hidden-radio" {% if seat_num == "3" %}checked{% endif %}>
                    <label for="rating3" class="seat-option">
                        {% if seat_num == "3" %}
                        <img src="{% static 'img/selected_seat.png' %}" alt="Image 3">
                        {% else %}
                        <img src="{% static 'img/seat.png' %}" alt="Image 3">
                        {% endif %}
                    </label>
                    <input type="radio" name="seat_num" id="rating4" value="4" class="hidden-radio" {% if seat_num == "4" %}checked{% endif %}>
                    <label for="rating4" class="seat-option">
                        {% if seat_num == "4" %}
                        <img src="{% static 'img/selected_seat.png' %}" alt="Image 4">
                        {% else %}
                        <img src="{% static 'img/seat.png' %}" alt="Image 4">
                        {% endif %}
                    </label>
                </div>
                <p class="error-msg">{{ error_msg_seat }}</p>
            </div>

            
            <div class="create-option-row">
                <div>
                    <input type="radio" name="max_num" value="3" id="rating3">
                    <label for="rating3">최대 3인 매칭</label>
                </div>
                <div>
                    <input type="radio" name="max_num" value="4" id="rating4" checked>
                    <label for="rating4">최대 4인 매칭</label>
                </div>
            </div>
        </div>
        <button type="submit" class="create-room-button">방 생성하기</button>
    </form>
</div>
<script>
    var staticSeatImage = "{% static 'img/seat.png' %}";
    var staticSelectedSeatImage = "{% static 'img/selected_seat.png' %}";
</script>
<script>
    $(document).ready(function(){
        $(document).ready(function(){
        // 기본적으로 선택된 라디오 버튼 값을 가져옴

        $(".seat-option img").click(function() {
            // 클릭한 이미지의 부모 라벨 요소
            var label = $(this).parent("label");
            // 클릭한 이미지의 연결된 input 요소
            var input = label.next("input[type='radio']");

            // 이미지 클래스가 disabled가 아닌 경우에만 처리
            if (!label.find("img").hasClass("disabled")) {
                // 이미지 클릭 시 연결된 input 체크
                input.prop("checked", true);

                // 모든 이미지 초기화 (선택되지 않은 상태로 변경)
                $(".seat-option img:not(.disabled)").attr("src", "{% static 'img/seat.png' %}");
                $(".seat-option img:not(.disabled)").removeClass("checked");
                // 클릭한 이미지만 선택된 이미지로 변경
                label.find("img").attr("src", "{% static 'img/selected_seat.png' %}");
                label.find("img").addClass("checked");
            }

        });
    });
    });
</script>
<script>
    const currentDate = new Date();
    const year = currentDate.getFullYear();
    const month = String(currentDate.getMonth() + 1).padStart(2, '0');
    const monthh = String(currentDate.getMonth() + 2).padStart(2, '0');
    const day = String(currentDate.getDate()).padStart(2, '0');
    const minDate = `${year}-${month}-${day}`;
    const maxDate = `${year}-${monthh}-${day}`;

    const selectedDateInput = document.getElementById('departure-date');
    selectedDateInput.min = minDate;
    selectedDateInput.max = maxDate;
</script>
{% endblock %}

templates/matching/matching_apply.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% endblock %}

{% block content %}
<!-- 모달 창 -->
{% if create_limit %}
<div class="modal fade" id="maxRoomsModal" tabindex="-1" aria-labelledby="maxRoomsModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="maxRoomsModalLabel">방 신청 제한</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                이미 3개 이상의 방에 참여하셨습니다. 더 이상 방에 참여할 수 없습니다.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        // 모달 띄우기
        $('#maxRoomsModal').modal('show');
    });
    $('#maxRoomsModal').on('hidden.bs.modal', function () {
            window.location.href = "{% url 'matching:main' %}";
        });
</script>
{% else %}
<div class="create-room">
    <form class="create-room-form" action="{% url 'matching:apply' matching_room.pk %}" method="post">
        {% csrf_token %}
        <div>
            <div class="direction-container">
                <div class="form-floating locations">
                    <input class="form-control" placeholder="" id="floatingTextarea" name="departure_area" value="{{ matching_room.departure_area }}" disabled></input>
                    <label for="floatingTextarea">출발 지점</label>
                </div>
                <img class="img-direction" src="{% static 'img/moveto.png' %}" alt="Image 2">
                <div class="form-floating locations">
                    <input class="form-control" placeholder="" id="floatingTextarea" name="departure_area" value="{{ matching_room.destination_area }}" disabled></input>
                    <label for="floatingTextarea">도착 지점</label>
                    
                </div>
            </div>

        </div>
        <hr>
        <div class="create-date-container">
            <div class="create-departure_date">
                <p>출발일</p>
                <input type="date" name="departure_date" id="create-departure_date" value="{{ matching_room.departure_date|date:'Y-m-d' }}" disabled>
            </div>
        </div>

        <hr>
        <div class="create-date-container">
            <div class="create-departure_time">
                <p>시간</p>
                <input type="time" class="form-control" value="{{ matching_room.departure_time|time:'H:i' }}" name="departure_time">
            </div>

        </div>
        <hr>
        <p class="apply-current_num">현재인원: {{matching_room.current_num}} / 최대인원: {{matching_room.max_num}}</p>
        <hr>
        <div class="create-container">
            <p>좌석 선택</p>
            <div class="create-option">
                <div class="seat-container">
                    <label for="rating0" class="seat-option">
                        <img src="{% static 'img/selected_seat.png' %}" alt="Image 0" class="disabled">
                    </label>
                    <input type="radio" name="seat_num" id="rating1" value="1" class="hidden-radio" {% if "1" in selected_seats %} 
                    disabled {% endif %}>
                    <label for="rating1" class="seat-option">
                        {% if "1" in selected_seats %} 
                            <img src="{% static 'img/selected_seat.png' %}" alt="Image 1" class ="disabled">
                        {% else %}
                            <img src="{% static 'img/seat.png' %}" alt="Image 1">
                        {% endif %}
                    </label>
                </div>
                <div class="seat-container">
                    <input type="radio" name="seat_num" id="rating2" value="2" class="hidden-radio" {% if "2" in selected_seats %} 
                    disabled {% endif %}>
                    <label for="rating2" class="seat-option">
                        {% if "2" in selected_seats %} 
                            <img src="{% static 'img/selected_seat.png' %}" alt="Image 2" class ="disabled">
                        {% else %}
                            <img src="{% static 'img/seat.png' %}" alt="Image 2">
                        {% endif %}
                    </label>
                    <input type="radio" name="seat_num" id="rating3" value="3" class="hidden-radio" {% if "3" in selected_seats %} 
                    disabled {% endif %}>
                    <label for="rating3" class="seat-option">
                        {% if "3" in selected_seats %} 
                            <img src="{% static 'img/selected_seat.png' %}" alt="Image 3" class ="disabled">
                        {% else %}
                            <img src="{% static 'img/seat.png' %}" alt="Image 3">
                        {% endif %}
                    </label>
                    <input type="radio" name="seat_num" id="rating4" value="4" class="hidden-radio" {% if "4" in selected_seats %} 
                    disabled {% endif %}>
                    <label for="rating4" class="seat-option">
                        {% if "4" in selected_seats %} 
                            <img src="{% static 'img/selected_seat.png' %}" alt="Image 4" class ="disabled" >
                        {% else %}
                            <img src="{% static 'img/seat.png' %}" alt="Image 4">
                        {% endif %}
                    </label>
                </div>
                <p class="error-msg">{{ error_msg_seat }}</p>
            </div>
        </div>
        <button type="submit" class="apply-room-button">방 신청하기</button>
    </form>
</div>
<script>
    var staticSeatImage = "{% static 'img/seat.png' %}";
    var staticSelectedSeatImage = "{% static 'img/selected_seat.png' %}";
</script>
<script>
    $(document).ready(function(){
        // 기본적으로 선택된 라디오 버튼 값을 가져옴

        $(".seat-option img").click(function() {
            // 클릭한 이미지의 부모 라벨 요소
            var label = $(this).parent("label");
            // 클릭한 이미지의 연결된 input 요소
            var input = label.next("input[type='radio']");

            // 이미지 클래스가 disabled가 아닌 경우에만 처리
            if (!label.find("img").hasClass("disabled")) {
                // 이미지 클릭 시 연결된 input 체크
                input.prop("checked", true);

                // 모든 이미지 초기화 (선택되지 않은 상태로 변경)
                $(".seat-option img:not(.disabled)").attr("src", "{% static 'img/seat.png' %}");
                $(".seat-option img:not(.disabled)").removeClass("checked");
                // 클릭한 이미지만 선택된 이미지로 변경
                label.find("img").attr("src", "{% static 'img/selected_seat.png' %}");
                label.find("img").addClass("checked");
            }

        });        
    });
</script>
{% endif %}

{% endblock %}

templates/matching/questions.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
{% endblock %}

{% block content %}


    <style>
       .logo-container {
            display: flex;
            margin-top: 10px;
            flex-direction: column; 
            align-items: center; 
            margin-bottom:13px;
        }

        .logo-container img {
            width: 160px;
            height: auto;
        }

        .logo-container h1 {
            font-size: 20px;
            font-weight: bold;
            margin: 0 5px; 
        }


       .faq-container {
            max-width: 800px;
         
            padding: 20px;
            background-color: white;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            margin-top: 50px;
        }

        .faq-item {
            margin-bottom: 20px;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 5px;
            background-color: #fff;
        }

        .question {
            font-weight: bold;
            color: #333;
            cursor: pointer;
        }

        .answer {
            margin-top: 5px;
            color: #666;
            display: none;
        }

        .faq-item.open .answer {
            max-height: 100px; /* 펼쳐진 높이 설정 */
            margin-top: 10px; /* 아래쪽 여백 추가 */
        }

        .faq-item.open .expand-icon {
            transform: rotate(180deg); /* 아이콘 회전시키기 */
        }
    </style>
</head>
<body>

        <div class="logo-container">
            <img src="{% static 'img/loginlogo_.png' %}" alt="로고 사진">
            <h1>자주 묻는 질문</h1>
        </div>
    
  
        <div class="faq-container">
            
                <div class="faq-item">
                    <div class="question">Q: 택시로카 서비스 이용방법이 궁금해요▼</div>
                    <div class="answer">

                        A: 택시로카 서비스는 다음과 같이 이용할 수 있습니다.<br>
                        1. 회원가입 후 로그인하기<br>
                        2. 휴가 날짜와 출발지, 도착지 입력하기<br>
                        3. 채팅방을 생성하거나 채팅방에 참가하여 동승자 구하기
                    </div>
                </div>
            <div class="faq-item">
                <div class="question">Q: 택시 예약은 안되나요? ▼ </div>
                <div class="answer">A: 택시로카는 택시 예약 서비스를 제공하고 있지 않습니다. <br>
                    휴가 나가는 군인들이 택시 동승자를 편리하게 구해 택시비를 절감할 수 있도록 돕습니다.</div>
            </div>
        
        </div>

    <script>
        
        document.addEventListener("DOMContentLoaded", function() {
            var questions = document.querySelectorAll(".question");
            
            questions.forEach(function(question) {
                question.addEventListener("click", function() {
                    var answer = this.nextElementSibling;
                    answer.style.display = answer.style.display === "block" ? "none" : "block";
                });
            });
        });
    </script>

{% endblock %}