apps/user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('main/', views.main, name='main'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'), 
    path('google/callback/', views.google_callback, name='google_callback'),
    path('send_email/', views.send_email, name='send_email'),
    path('activate/<int:pk>/', views.activate_account, name='activate_account'),
    path('login/social/', views.social_login,name='social_login'),
    path('kakao/redirect/',views.kakao_Auth_Redirect,name="kakaoAuth"), # 카카오디벨로퍼스
    path('mypage/',views.mypage,name="mypage"),
    path('modify/',views.modify,name="modify"),
]

taxiRoka/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='matching/')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('chat/', include('apps.chat.urls')),
    path('matching/', include('apps.matching.urls')),
    path('user/', include('apps.user.urls')),
    path('vacation/', include('apps.vacation.urls')),
    path('report/', include('apps.report.urls')),
]

apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

# ERD CLOUD 링크: https://www.erdcloud.com/d/zB3wiAaQY7PxnzLyY

class Location(models.TextChoices):
    Sangmudae = 'Sangmudae', '상무대' 

class CustomUser(AbstractUser):
    # 아이디, 비밀번호, 이름, 전화번호, 이메일, 부대위치, 신고횟수, 가입일, 입대일, 전역일, 알림수
    phone = models.CharField(max_length=11)
    location = models.CharField(max_length=10, choices=Location.choices)
    count = models.IntegerField(default=0)
    join_date = models.DateTimeField(default=timezone.now)
    in_date = models.DateField(null=True,blank=True)
    out_date = models.DateField(null=True,blank=True)
    kakaoId = models.IntegerField(null=True,blank=True)

apps/user/forms.py
from django import forms
from .models import CustomUser

class SignupForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password', 'phone', 'location', 'in_date', 'out_date']

apps/user/views.py
from django.shortcuts import render, redirect
from django.contrib import auth, messages
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth import login as authlogin
from django.contrib.auth.forms import UserChangeForm
from allauth.account.views import LoginView
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .models import CustomUser
from apps.matching.models import MatchingRoom, Matching 
from apps.vacation.models import Vacation
from django.http import Http404
from django.contrib.auth.backends import ModelBackend
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from decouple import config
import requests
import smtplib
import os

User = get_user_model()

def main(request):
    return render(request, 'user/main.html')

def login(request):
    if request.method == 'POST':
        email = request.POST['email']  
        password = request.POST['password']

        user = auth.authenticate(request, username=email, password=password)

        if user is None:
            messages.error(request, '이메일 또는 비밀번호가 올바르지 않습니다.')
            return redirect(reverse('user:login'))
            
        else:
            print('login')
            auth.login(request, user)
            user = CustomUser.objects.get(username=user.username)
            return redirect('matching:main')
    return render(request, 'user/login.html') 

@login_required
def google_callback(request):
    user = request.user
    if not user.location:  # location이 비어있다면
        # 추가 정보 입력 페이지로 이동
        return redirect('user:social_login')
    else:
        # 메인 페이지로 이동
        return redirect('matching:main')

def social_login(request):   
    if request.method == 'POST':
        user = request.user  # 현재 로그인한 유저 정보
        # 만약 user의 location이 비어있으면
        if not user.location:
            name = request.POST['first_name']
            phone = request.POST['phone']
            location = request.POST['location']

            # 업데이트
            user.first_name = name
            user.last_name = ''
            user.username = user.email  # email 업데이트
            user.phone = phone  # phone 업데이트
            user.location = location  # location 업데이트
            user.save()
        return redirect('matching:main')  # 메인 페이지로 리디렉트
    if not request.user.location:
        return render(request, 'user/social.html')
    return redirect('matching:main')

def logout(request) :
    auth.logout(request)
    return redirect(reverse('user:main'))

def signup(request):   
    if request.method == 'POST':
        first_name = request.POST['first_name'] 
        email = request.POST['email']
        password = request.POST['password']
        phone = request.POST['phone']
        location = request.POST['location']
        
        hashed_password = make_password(password)

        user, created = CustomUser.objects.get_or_create(
            email=email,
            defaults={
                'first_name': first_name,
                'username': email,
                'password': hashed_password,
                'phone': phone,
                'location': location,
                'is_active': False,
            }
        )

        if not created:
            messages.error(request, '이미 존재하는 이메일입니다. 인증 이메일을 확인해주세요.')
            return redirect(reverse('user:signup'))

        if created:
    # 새로운 객체가 생성된 경우
            user.backend = f'{ModelBackend.__module__}.{ModelBackend.__qualname__}'
            user.save()
            send_activation_email(user)
            return redirect('user:send_email')
        else:
    # 이미 객체가 존재하는 경우
            return render(request, 'user/signup.html', {'error_message': '이미 해당 이메일로 가입된 유저가 있습니다.'})

    return render(request, 'user/signup.html')


def send_activation_email(user):
    try:
        smtp_server = smtplib.SMTP('smtp.gmail.com', 587)
        smtp_server.starttls()
        smtp_server.login(config("EMAIL_HOST_USER"), config("EMAIL_HOST_PASSWORD"))

        subject = '[TaxiRoka] 본인 확인을 위한 이메일 인증을 완료해주세요!'
        activation_link = f'https://taxiroka.p-e.kr/user/activate/{user.pk}/'
        
        sender_email = config("EMAIL_HOST_USER")
        recipient_email = user.email

        email_body = f'''
            <html>
                <body>
                    <h1>이메일 인증</h1>
                    <h3><br>서비스 이용을 위해 가입한 계정이 본인인지 확인하려고 합니다. <br>아래 버튼을 눌러 이메일 인증을 해주세요.<br></h3>
                    <a href="{activation_link}">
                        <button style="background-color: #007BFF; color: white; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer;">
                            인증하기
                        </button>
                    </a>
                </body>
            </html>
        '''

        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = recipient_email
        msg['Subject'] = subject
        msg.attach(MIMEText(email_body, 'html'))  # HTML message
        smtp_server.sendmail(sender_email, recipient_email, msg.as_string())

    except smtplib.SMTPException as e:
        print("An error occurred:", str(e))
    finally:
        smtp_server.quit()


def activate_account(request, pk):
    User = get_user_model()

    try:
        user = User.objects.get(pk=pk)
    except User.DoesNotExist:
        raise Http404("User does not exist")

    user.is_active = True
    user.save()

    return render(request, 'user/account_activated.html')


def send_email(request):
    return render(request, 'user/send_email.html')  


def kakao_Auth_Redirect(request):
    code = request.GET.get('code',None)
    print("함수호출횟수",code)
    if code:
        print("code", code)
        #이제 토큰을 받아야함.
        headers = {
        'Content-type':'application/x-www-form-urlencoded;charset=utf-8'
        }
        content = {
        "grant_type": "authorization_code",
        "client_id": config("KAKAO_CLIENT_ID"),
        "redirect_url": "https://taxiroka.p-e.kr/user/kakao/redirect",
        "code": code,
        }
        res = requests.post("https://kauth.kakao.com/oauth/token",headers=headers, data=content)
        print(res)
        if res.status_code == 200:
            print("성공")
            token_res = res.json()
            headers123 = {
                "Authorization" : "Bearer " + token_res['access_token'],
                "Content-type": "application/x-www-form-urlencoded;charset=utf-8",
            }
            res = requests.post("https://kapi.kakao.com/v2/user/me",headers=headers123)
            print("res2", res)
            if res.status_code == 200:
                profile_res = res.json()
                username = profile_res['properties']['nickname']
                kakao_email = profile_res['kakao_account']['email']
                id = profile_res['id']
                user = User.objects.filter(email=kakao_email).first()
                print(id, username)
                if user is not None:
                    print("로그인")
                    authlogin(request, user, backend='django.contrib.auth.backends.ModelBackend')
                    return redirect('user:social_login')
                else:
                    print("새로 생성")
                    user = User()
                    print(user)
                    user.username = kakao_email 
                    print(user.username)
                    user.first_name = username
                    user.email = kakao_email
                    user.kakaoId = id
                    user.save()
                    authlogin(request, user, backend='django.contrib.auth.backends.ModelBackend')
                    return redirect('user:social_login')
            else:
                print("user정보 가져오기 실패")
        else:
            print("토근발급 실패")
    

    return redirect("/")

# 마이페이지
def mypage(request):
    matching_all = Matching.objects.filter(user_id = request.user).count()
    matching_ing = Matching.objects.filter(user_id = request.user, matching_room_id__end_yn = True).count()
    matching_end = Matching.objects.filter(user_id = request.user, matching_room_id__end_yn = False).count()
    vacations = Vacation.objects.filter(user_id = request.user)

    ctx= {
        "matching_all": matching_all,
        "matching_ing": matching_ing,
        "matching_end": matching_end,
        "vacations":vacations,
    }

    return render(request, 'user/mypage.html', context=ctx)

@login_required
def modify(request):
    user = request.user

    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        phone = request.POST.get('phone')
        location = request.POST.get('location')

        user.first_name = first_name
        user.phone = phone
        user.location = location
        user.save()

        messages.success(request, '사용자 정보가 수정되었습니다.')
        return redirect('/user/mypage/')

    context = {
        'user': user,  # 수정된 사용자 정보를 넘겨줍니다.
    }

    return render(request, 'user/modify.html', context)

templates/user/account_activated.html
{% extends './base.html' %}{% load static %}
{% block content %}


    <style>
        .main_container {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            text-align: center;
            
        }

        .container {
            margin-top:130px;
            background-color: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            
        }

        .email-image {
            display: inline-block;
            vertical-align: middle;
            margin-right: 15px; 
        }

        h1 {
            color: #333;
            font-size: 20px;
            margin-bottom: 10px;
            display: inline-block;
            vertical-align: middle;
        }

        p {
            color: #777;
            font-size: 15px;
            margin-top: 10px;
        }

        .button-container {
            margin-top: 20px;
        }

        .custom-button {
            padding: 10px 20px;
            background-color: #777;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
    </style>

<div class="main-container">
    <div class="container">
        <img class="email-image" src="{% static 'img/email.png' %}" alt="이메일로고사진">
        <h1>회원가입 완료!</h1>
        <p>서비스 이용을 위해 가입한 계정으로 <br>로그인 해주세요.</p>
        <div class="button-container">
            <button class="custom-button" onclick="window.location.href='/user/main/'">로그인 하러가기</button>
        </div>
    </div>
</div>

{% endblock %}

templates/user/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
    <title>Taxi Roka</title>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/user/main.css' %}">
</head>

<body>
    {% block content %}
    {% endblock %}
    <script src="https://kit.fontawesome.com/6fbcf91afd.js" crossorigin="anonymous"></script>
</body>
</html>

templates/user/kakao-signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Signup</title>
</head>
<body>
<form method="POST">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group {% if field.errors|length > 0 %}has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        <input name="{{ field.html_name }}" id="{{ field.id_for_lable }}" class="form-control"
               type="{{ field.field.widget.input_type }}" value="{{ field.value|default_if_none:'' }}">
        {% for error in field.errors %}
            <label class="control-label" for="{{ field.id_for_label }}">{{ error }}</label>
        {% endfor %}
    {% endfor %}
    <div class="form-actions">
        <button type="submit">회원가입하기</button>
    </div>
    </div>
</form>
</body>
</html>

templates/user/login.html
{% extends './base.html' %}{% load static %}
{% block content %}

<div class="login-container">
    <form method="POST" action="{% url 'user:login' %}" class="login-form">
        {% csrf_token %}
    
        <h1 style="font-size: 0;">
            Taxi Roka
            <img src="{% static 'img/loginlogo_.png' %}" alt="메인페이지 로고사진">
        </h1>
    
    
        <div class="login-container">
            <div class="input-group">
                <img src="{% static 'img/user-solid.svg' %}">
                <input
                    type="email"
                    class="form-control"
                    name="email"
                    placeholder="이메일을 입력하세요"
                />
            </div>
            <div class="input-group">
                <img src="{% static 'img/lock-solid.svg' %}">
                <input
                    type="password"
                    class="form-control"
                    name="password"
                    placeholder="비밀번호를 입력하세요"
                />
            </div>
            <button type="submit">로그인</button>
            
            <div class="login-error-messages">
                {% for message in messages %}
                    <ul>
                        {{ message }}
                    </ul>
                {% endfor %}
                
                    
            </div>
        </div>
    </form>

</div>

<div id="myModal" class="loginmodal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <p>올바른 회원 정보를 입력하세요.</p>
    </div>
</div>


<!--모달CSS만-->
<style>
    .login-error-messages {
    color: red;
    font-size: 10px;
    margin-top: 0px;
      }

    .loginmodal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0, 0, 0, 0.5);
    }
 
    .modal-content {
        background-color: #fefefe;
        margin: 15% auto;
        padding: 20px;
        border: 1px solid #888;
        width: 80%;
        max-width: 400px;
        border-radius: 5px;
        position: relative;
    }
 
    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }
 
    .close:hover,
    .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }
 </style>
 
{% endblock %}

templates/user/modify.html
{% extends 'base.html' %}{% load static %}
{% block content %}

<div class="logout-container">
  <form method="POST" action="{% url 'user:modify' %}">
      {% csrf_token %}
      <h1>회원정보 수정</h1>
    <!--이메일은 수정 못하게-->
      <div class="form-group">
        <label for="inputEmail3">이메일</label>
        <input type="email" class="form-control" id="inputEmail3" name="email" value="{{ user.email }}" disabled/>
      </div>
  
      <div class="form-group">
        <label for="inputPassword3">비밀번호</label>
        <input
          type="password"
          class="form-control"
          id="inputPassword3"
          name="password"
          value="********"
          disabled
        />
      </div>
      <div class="form-group">
        <label for="inputPassword3">비밀번호 확인</label>
        <input
          type="password"
          class="form-control"
          id="confirminputPassword3"
          name="confirm_password"
          value="********"
          disabled
        />
      </div>
      <div class="form-group">
        <label for="id_first_name">이름</label>
        <input type="text" class="form-control" id="id_first_name" name="first_name" value="{{ user.first_name }}" required/>
      </div>
      <div class="form-group">
        <label for="inputPhone">전화번호</label>
        <input type="tel" class="form-control" id="inputPhone" name="phone" value="{{ user.phone }}" required/>
      </div>
      <div class="form-group">
        <label for="inputLocation">부대위치</label>
        <select class="form-control" id="inputLocation" name="location">
          <option value="Sangmudae" {% if user.location == "Sangmudae" %}selected{% endif %}>상무대</option>
        </select>
      </div>
      <div class="modify-button">
      <button type="submit" id="signupBtn">수정완료</button>
      </div>
  </form>
  

  <div id="myModal" class="modal" style="display: none;">
    <div class="modal-content">
        <span class="close">&times;</span>
        <p>회원정보 수정이 완료되었습니다!</p>
    </div>
  </div>

</div>

      
  


    

<!-- 모달 HTML -->
<div id="modalMismatchPassword" class="modal" style="display: none;">
  <div class="modal-content">
    <span class="close">&times;</span>
    <p>비밀번호가 일치하지 않습니다. <br><br>다시 확인해주세요.</p>
  </div>
</div>

<div id="modalEmptyFields" class="modal" style="display: none;">
  <div class="modal-content">
    <span class="close">&times;</span>
    <p>모든 필드를 입력해주세요.</p>
  </div>
</div>

<div id="modalShortPassword" class="modal" style="display: none;">
  <div class="modal-content">
    <span class="close">&times;</span>
    <p>비밀번호는 8자리 이상이어야 합니다. <br><br>다시 확인해주세요.</p>
  </div>
</div>

<div id="modifySuccessModal" class="modal" style="display: none;">
  <div class="modal-content">
    <span class="close">&times;</span>
    <p>회원정보 수정이 완료되었습니다!</p>
  </div>
</div>



<style>
.logout-container {
  display: flex;
  justify-content: center;
}

.logout-container button {
  background-color: var(--button-color);
  color: white;
  border: none;
  padding: 8px 16px;
  cursor: pointer;
  transition: background-color 0.3s;
  margin-bottom: 10px; 
  border-radius: 15px;
}

.modify-button {
  margin-top: 50px;
  text-align: center;
}

.logout-container h1 {
  text-align: center;
  margin-bottom: 40px;
}
.form-group {
  margin-top: 20px;
}
/* 부대위치 입력 박스 스타일 */
.form-group #inputLocation {
      background-color: #f5f5f5; 
      border: 1px solid #101010; 
      padding: 8px; 
      width: 100%; 
      border-radius: 10px; 
      font-size: 14px;
      cursor: pointer; 
      margin-bottom: 10px;
  }  

.signup-error-messages {
    color: red;
    font-size:10px;
    margin-top: 6px;
    text-align: center;
}

.modal {
  display: none;
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  align-items: center;
  justify-content: center;
}

.modal-content {
  background-color: white;
  padding: 20px;
  border-radius: 5px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
  text-align: center;
  
}

.close {
  position: absolute;
  top: 10px;
  right: 10px;
  font-size: 20px;
  cursor: pointer;
}



</style>
<script>
const form = document.querySelector('form');
const modalEmptyFields = document.getElementById('modalEmptyFields');
const modifySuccessModal = document.getElementById('modifySuccessModal');

form.addEventListener('submit', (event) => {
  const inputs = form.querySelectorAll('input, select');
  let allFieldsFilled = true;

  inputs.forEach((input) => {
    if (!input.value) {
      allFieldsFilled = false;
    }
  });

  if (!allFieldsFilled) {
    event.preventDefault(); 
    modalEmptyFields.style.display = 'block';
  } else {
    // 모든 필드가 입력되었을 때만 수정 성공 모달을 나타냅니다.
    modifySuccessModal.style.display = 'block';
    setTimeout(() => {
      modifySuccessModal.style.display = 'none';
    }, 3000);
  }
});

// 외부 클릭시 모달 닫기 이벤트 리스너 추가
const modals = document.querySelectorAll('.modal');
modals.forEach((modal) => {
  modal.addEventListener('click', (event) => {
    if (event.target === modal) {
      modal.style.display = 'none';
    }
  });

  const closeButton = modal.querySelector('.close');
  closeButton.addEventListener('click', () => {
    modal.style.display = 'none';
  });
});


  
</script>-->

<script>
  const form = document.querySelector('form');
  const modalEmptyFields = document.getElementById('modalEmptyFields');
  const modifySuccessModal = document.getElementById('modifySuccessModal');

  form.addEventListener('submit', async (event) => {
    event.preventDefault();

    const inputs = form.querySelectorAll('input, select');
    let allFieldsFilled = true;

    inputs.forEach((input) => {
      if (!input.value) {
        allFieldsFilled = false;
      }
    });

    if (!allFieldsFilled) {
      modalEmptyFields.style.display = 'block';
    } else {
      // 서버에 수정 요청 전송
      const response = await fetch(form.action, {
        method: 'POST',
        body: new FormData(form),
        headers: {
          'X-CSRFToken': '{{ csrf_token }}',
        },
      });

      if (response.ok) {
          // 성공적으로 수정되었을 때 모달 띄우기
          // modifySuccessModal.style.display = 'block';
          setTimeout(() => {
            modifySuccessModal.style.display = 'none'; 
          }, 5000); // 5초 후에 모달을 자동으로 닫도록 설정
      } else {
          // 에러 처리
      }
    }
  });

  // 외부 클릭시 모달 닫기 이벤트 리스너 추가
  const modals = document.querySelectorAll('.modal');
  modals.forEach((modal) => {
    modal.addEventListener('click', (event) => {
      if (event.target === modal) {
        modal.style.display = 'none';
      }
    });

    const closeButton = modal.querySelector('.close');
    closeButton.addEventListener('click', () => {
      modal.style.display = 'none';
    });
  });
</script>


<script src="{% static 'js/signup.js' %}"></script>
{% endblock %}

templates/user/mypage.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
{% endblock %}

{% block content %}

<div class="logo-container">
    <img src="{% static 'img/loginlogo_.png' %}" alt="로고 사진">

    <div class="mypage-banner">
        <img src="{% static 'img/banner_mypage.png' %}" alt="배너사진">
    </div>
</div>


<div class="mypage-container">

    <div class="profile-top-container">
        <div class="profile-picture">
            <img src="{% static 'img/mypage2.png' %}" alt="프로필 사진">
        </div>
        <div class="profile-info">
            <div class="profile-name">
                <h1>{{user.username}}</h1>
            </div>
            <div class="profile-intro">
                <p>{{user.location}}</p>
            </div>
        </div>
    </div>
        

    <div class="profile-info-container">
        <div class="profile-info">
            <div class="info-row">
                <div class="info-label">이름:</div>
                <div class="info-value">&nbsp;&nbsp;{{user.first_name}}</div>
            </div>
            <div class="info-row">
                <div class="info-label">이메일:</div>
                <div class="info-value">&nbsp;&nbsp;{{user.username}}</div>
            </div>
           
            <div class="info-row">
                <div class="info-label">전화번호:</div>
                <div class="info-value">&nbsp;&nbsp;{{user.phone}}</div>
            </div>
            <div class="info-row">
                <div class="info-label">부대위치:</div>
                <div class="info-value">&nbsp;&nbsp;{{user.location}}</div>
            </div>
        </div>
    </div>
    
    
    <div class="section">
        <h2>매칭 이력</h2>
        <div class="match-history">
            <div class="match-status">
                <h3>전체</h3>
                <p class="match-count">{{matching_all}}</p>
               
            </div>
            <div class="match-status">
                <h3>예정</h3>
                <p class="match-count-reservation">{{matching_ing}}</p>
               
            </div>
            <div class="match-status">
                <h3>완료</h3>
                <p class="match-count">{{matching_end}}</p>
               
            </div>
        </div>
    </div>
    
    <div class="section">
        <h2>휴가 이력</h2>
        <div class="vacation-history">
            {% if vacations|length != 0 %}
            {% for vacation in vacations %}
            <div class="vacation-status">
                <div class="vacation-departure">
                    <div class="vacation-label"><h3>휴가 신청일</h3></div>
                    <div class="vacation-content">{{ vacation.departure_date }}</div>
                </div>                 
                <div class="vacation-arrow">
                    <img src="{% static 'img/arrow_right2.png' %}" alt="화살표">
                </div>
                <div class="vacation-arrival">
                    <div class="vacation-label"><h3>휴가 복귀일</h3></div>
                    <div class="vacation-content">{{ vacation.arrival_date }}</div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="vacation-status">
                <h3>등록된 휴가 일정이 없습니다.</h3> 
                <h3>휴가 복귀일: {{ vacation.arrival_date }}</h3>
            </div>
            {% endif %}
        </div>
    </div>

    <div class="profile-actions">
        <a href="{% url 'user:modify' %}">
        <button class="edit-profile-button">회원정보 수정</button>
        </a>
        <a href="{% url 'user:logout' %}">
        <button class="logout-button">&nbsp;&nbsp;&nbsp;&nbsp;로그아웃&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</button>
        </a>
    </div>
</div>
 
<!-- 수정    
<div class="mypage-container">
    <div class="mypage-banner">
        <img src="{% static 'img/banner_mypage.png' %}" alt="배너사진">
    </div>
    <div class="mypage-content">
        <div class="profile-img">
            <img src="{% static 'img/army_tag.png' %}" alt="프로필사진">
        </div>
        <div class="profile-content">
            <div class="user-name">
                {{user.first_name}}
            </div>            
            <div class="user-location">
                {{user.location}}
            </div>
            <div class="user-detail-info">
                <div class="user-detail-label">
                    <div class="user-email-label">이메일:</div>
                    <div class="user-phone-label">전화번호:</div>
                </div>
                <div class="user-detail-content">
                    <div class="user-email-content">{{user.email}}</div>
                    <div class="user-phone-content">{{user.phone}}</div>
                </div>
            </div>
        </div>
    </div>
    <div class="section">
        <h2>휴가 이력</h2>
        <div class="vacation-history">
            {% if vacations|length != 0 %}
            {% for vacation in vacations %}
            <div class="vacation-status">
                <div class="vacation-departure">
                    <div class="vacation-label"><h3>휴가 신청일</h3></div>
                    <div class="vacation-content">{{ vacation.departure_date }}</div>
                </div>                 
                <div class="vacation-arrow">
                    <img src="{% static 'img/arrow_right2.png' %}" alt="화살표">
                </div>
                <div class="vacation-arrival">
                    <div class="vacation-label"><h3>휴가 복귀일</h3></div>
                    <div class="vacation-content">{{ vacation.arrival_date }}</div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="vacation-status">
                <h3>등록된 휴가 일정이 없습니다.</h3> 
                <h3>휴가 복귀일: {{ vacation.arrival_date }}</h3>
            </div>
            {% endif %}
        </div>
    </div>

    <div class="profile-actions">
        <a href="{% url 'user:modify' %}">
        <button class="edit-profile-button">회원정보 수정</button>
        </a>
        <a href="{% url 'user:logout' %}">
        <button class="logout-button">&nbsp;&nbsp;&nbsp;&nbsp;로그아웃&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</button>
        </a>
    </div>
</div>
  

-->
{% endblock %}